#!/bin/sh
set -e
package_name=flash-javaws-widevine-fonts
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/itweb-settings.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/itweb-settings.desktop"
;;
esac
exit 0
